image:
  file: .gitpod.Dockerfile

tasks:
  - name: Set Java 21 Environment
    init: |
      echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64' >> ~/.bashrc
      echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH

  - name: Verify Java
    init: |
      source ~/.bashrc
      java -version

  - name: Backend Build
    init: |
      source ~/.bashrc
      cd Backend/Corporateapp/Corporateapp && ./mvnw clean install
    command: |
      source ~/.bashrc
      cd Backend/Corporateapp/Corporateapp && ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
