image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Java 21
    init: |
      ./setup-java21.sh
      source ~/.bashrc

  - name: Verify Java
    init: |
      source ~/.bashrc
      java -version

  - name: Backend
    init: |
      source ~/.bashrc
      cd Backend/Corporateapp/Corporateapp && ./mvnw clean install
    command: |
      source ~/.bashrc
      cd Backend/Corporateapp/Corporateapp && ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview